version: '3.7'

services:
  db_task:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password  
    container_name: mysql-task
    volumes:
      - mysql_task:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
    restart: unless-stopped
    env_file: .env 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}    
volumes:
  mysql_task:
